name: frarosrap
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
jobs:
  Docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses:  phwes/simple_hello_world@v1
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'     
      - name: Generando la documentación
        run: |
          chmod +x gradlew        
          ./gradlew javadoc

